- wrongsecrets-balancer/src/kubernetes.js
Additional fixes for https://github.com/commjoen/wrongsecrets/issues/403 : fixes liveness/readiness/challenge8
> Adding livenesss/readiness updates, challenge8 fix

- wrongsecrets-balancer/src/kubernetes.js
- Fixed the NSP to talk to WrongSecrets balancer to `WrongSecrets` and `VirtualDesktop` in namespaces.
> Fixed NSP to allow from Balancer

- wrongsecrets-balancer/ui/src/cards/InstanceRestartingCard.js
- wrongsecrets-balancer/ui/src/pages/JoinPage.js
if the automated CTFD entry generation is used, then sshow the extra domain in the listing, otherwise just show 2.
> Dynamicly reference extra domain

- .gitignore
- scripts/list-unused-ns.sh
- wrongsecrets-balancer/package-lock.json
- wrongsecrets-balancer/package.json
- wrongsecrets-balancer/src/teams/teams.js
- wrongsecrets-balancer/ui/package-lock.json
> Updated outdated javascript deps, updated listing script

- aws/main.tf
- aws/s3-user.tf
- helm/wrongsecrets-ctf-party/values.yaml
Updated latest deps in balancer (1.5B), worngsecrets and desktop (1.5.11) and fixed deprecated TF usage
> Updated latest deps in balancer (1.5B), worngsecrets and desktop (1.5.11) and fixed deprecated TF usage

- aws/README.md
- aws/build-an-deploy-aws.sh
- aws/cleanup-aws-autoscaling-and-helm.sh
- aws/cluster-autoscaler-policy.json
- aws/s3-user.tf
- aws/terraform.tfvars
- helm/wrongsecrets-ctf-party/values.yaml
> Migrate to 1.5.13 of WrongSecrets

- cleaner/.jest/setEnvVars.js
- cleaner/jest.config.js
- cleaner/package-lock.json
- cleaner/package.json
- cleaner/src/kubernetes.js
- cleaner/src/logger.js
- cleaner/src/main.js
- cleaner/src/main.test.js
- helm/wrongsecrets-ctf-party/templates/cleanup/cron-job.yaml
- helm/wrongsecrets-ctf-party/values.yaml
> feat: make cleaner delete full namespace

- helm/wrongsecrets-ctf-party/values.yaml
-   [x] Platform support (materialized new version of the cleaner container)
Checklist:
> Update version of cleaner

- readme.md
-   [x] Additional documentation
Checklist:
-   [ ] All the contributions made are solely the work of me and my co-authors
-   [ ] The PR passes pre-commit hooks and automated tests
> Added @osamamagdy to the contributor list

- .github/workflows/pre-commit.yml
-   [x] A new feature
Checklist:
> feat: add pre-commit ci lite

- wrongsecrets-balancer/src/kubernetes.js
Checklist:
-   [x] I added tests to ensure my change works (if applicable)
> fix(#noticket): balancer query now continues when contianer is not yet found

- helm/wrongsecrets-ctf-party/templates/wrongsecrets-balancer/deployment.yaml
- helm/wrongsecrets-ctf-party/values.yaml
- package-lock.json
- package.json
- readme.md
- wrongsecrets-balancer/src/__mocks__/kubernetes.js
- wrongsecrets-balancer/src/kubernetes.js
- wrongsecrets-balancer/src/teams/teams.js
- wrongsecrets-balancer/src/teams/teams.test.js
-   [x] Something else: adding challenge33 and vault dev container (WIP)
Checklist:
-   [x] I added tests to ensure my change works (if applicable)
TODO:
> Add challenge 33 and Vault

- helm/wrongsecrets-ctf-party/values.yaml
- wrongsecrets-balancer/src/proxy/proxy.js
- wrongsecrets-balancer/src/teams/teams.js
- wrongsecrets-balancer/ui/src/App.test.js
- wrongsecrets-balancer/ui/src/cards/InstanceRestartingCard.js
- wrongsecrets-balancer/ui/src/cards/InstanceStatusCard.js
- wrongsecrets-balancer/ui/src/index.js
- wrongsecrets-balancer/ui/src/pages/JoinPage.js
- wrongsecrets-balancer/ui/src/translations/de-DE.js
- wrongsecrets-balancer/ui/src/translations/nl-NL.js
-   [x] Fixes or refactors : fixes breaking changes from styled components migration, fixes regex bugs
Checklist:
TODO:
> Fixes for react components and other items

- .github/workflows/pages.yml
-   [x] A new feature
Checklist:
> feat: add pages workflow

- .github/workflows/publish.yml
> fix: allow workflow dispatch on publish

- .github/workflows/pages.yml
> fix: checkout pages branch in pages workflow

- .github/workflows/minikube-k8s-test.yml
- aws/build-and-deploy-aws.sh
- azure/k8s/secret-challenge-vault-deployment.yml.tpl
- build-and-deploy-container-minikube.sh
- build-and-deploy-container.sh
- build-and-deploy-minikube.sh
- build-and-deploy.sh
- helm/wrongsecrets-ctf-party/Chart.yaml
- helm/wrongsecrets-ctf-party/README.md
- helm/wrongsecrets-ctf-party/values.yaml
- readme.md
> fix: bump to 1.6.9 and correct name error

- guides/azure/azure.md
- guides/gcp/gcp.md
- readme.md
-   [X] Additional documentation
Checklist:
-   [X] All the contributions made are solely the work of me and my co-authors
-   [X] The PR passes pre-commit hooks and automated tests
> docs: update readme for gcp and azure support

- .github/workflows/minikube-k8s-test.yml
- aws/README.md
- aws/variables.tf
- azure/README.md
- azure/variables.tf
- build-and-deploy-container-minikube.sh
- build-and-deploy-minikube.sh
- gcp/README.md
- gcp/variables.tf
- readme.md
-   [x] Platform support: upgrade k8s to 1.28
Checklist:
> Upgrade to k8s 1.28

- .github/dependabot.yml
> Update dependabot.yml to allow for more prs

- wrongsecrets-balancer/ui/package-lock.json
- wrongsecrets-balancer/ui/src/App.js
Checklist:
-   [ ] All the contributions made are solely the work of me and my co-authors
-   [ ] The PR passes pre-commit hooks and automated tests
> Source fixes and dep vuln fixes

- .github/workflows/minikube-k8s-test.yml
- aws/.terraform.lock.hcl
- aws/README.md
- aws/build-and-deploy-aws.sh
- aws/shared-state/.terraform.lock.hcl
- aws/variables.tf
- azure/README.md
- azure/build-and-deploy-azure.sh
- azure/shared-state/.terraform.lock.hcl
- azure/variables.tf
- build-and-deploy-container-minikube.sh
- build-and-deploy-minikube.sh
- cleaner/package-lock.json
- gcp/README.md
- gcp/build-and-deploy-gcp.sh
- gcp/main.tf
- gcp/secrets.tf
- gcp/shared-state/main.tf
- gcp/variables.tf
- readme.md
- wrongsecrets-balancer/package-lock.json
- wrongsecrets-balancer/src/kubernetes.js
- wrongsecrets-balancer/src/teams/teams.js
- wrongsecrets-balancer/ui/package-lock.json
- wrongsecrets-balancer/ui/package.json
- wrongsecrets-balancer/ui/src/pages/AdminPage.js
-   [x] Platform support: updated to k8s 1.30
Takes care of 1 task of https://github.com/OWASP/wrongsecrets-ctf-party/issues/664
Checklist:
-   [x] updated and tested AWS
-   [x] updated and tested azure
-   [x] updated and tested gcp
-   [x] updated and tested minikube
> update k8s to 1.30 on all platforms

- aws/main.tf
Checklist:
-   [x] I added tests to ensure my change works (if applicable)
> fix: make managed node group name pretty

- .github/workflows/pre-commit.yml
Checklist:
-   [ ] The PR passes pre-commit hooks and automated tests
> fix: have bot PRs autofixed by renovate
